name: air_horn
version: 1.0.1+2
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter

  flutter_svg: ^1.1.5

  percent_indicator: ^4.2.2

  just_audio: ^0.9.29

  bot_toast: ^4.0.1

  google_mobile_ads: ^2.0.1

  share_plus: ^5.0.0

  url_launcher: ^6.1.6

  http: ^0.13.5

  shared_preferences: ^2.0.15

  firebase_core: ^2.2.0
  firebase_analytics: ^10.0.5

  #  <------------------------- Firebase In App Messaging ---------------->
  firebase_in_app_messaging: ^0.7.0+5
  firebase_messaging: ^14.1.0


dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

  flutter_launcher_icons: ^0.10.0
flutter_icons:
  image_path: "assets/logo.png"
  android: true
  ios: true

flutter:
  assets:
    - assets/
    - assets/categories/

    - assets/FilmEffect/
    - assets/FilmEffect/sounds/

    - assets/People/
    - assets/People/sounds/

    - assets/Nature/
    - assets/Nature/sounds/

    - assets/House Hold/
    - assets/House Hold/sounds/

    - assets/City/
    - assets/City/sounds/

    - assets/Musical/
    - assets/Musical/sounds/

    - assets/Technology/
    - assets/Technology/sounds/

    - assets/Horror/
    - assets/Horror/sounds/

  uses-material-design: true

